config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '(:locale)', locale: /es|en/ do
    root to: 'pages#home'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    get 'home', to: 'pages#home', as: :home
    get 'service_1', to: 'pages#service_1', as: :service_1
    get 'service_2', to: 'pages#service_2', as: :service_2
    get 'service_3', to: 'pages#service_3', as: :service_3
    get 'service_4', to: 'pages#service_4', as: :service_4
    get 'service_5', to: 'pages#service_5', as: :service_5

    get 'about', to: 'pages#about', as: :about
    get 'gallery', to: 'pages#gallery', as: :gallery
    get 'gallery-single', to: 'pages#gallery-single', as: :gallery_single
    get 'contact', to: 'pages#contact', as: :contact
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :phone, phone: true, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true
  validates :comment, length: { minimum: 20, maximum: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  around_action :switch_locale

    def switch_locale(&action)
      locale = params[:locale] || I18n.default_locale
      I18n.with_locale(locale, &action)
    end

    def default_url_options
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def service_1
  end

  def service_2
  end

  def service_3
  end

  def service_4
  end

  def service_5
  end

  def gallery
  end

  def gallery_single
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/pages/_breadcrumbs.html.erb
<section class="page_title ds s-pt-100 s-pb-50 s-pt-md-75 s-pb-md-25 breadcrumbs">
  <div class="container">
    <div class="row">

      <div class="d-none d-lg-block divider-90"></div>

      <div class="col-md-12 text-center">
        <%= cl_image_tag "logo-rgm_o34ajj", width: 400, height: 400 %>
      </div>

      <div class="d-none d-lg-block divider-15"></div>

    </div>
  </div>
</section>

app/views/pages/_gallery.html.erb
<section class="s-py-0 container-px-0 gallery-main ds" id="gallery">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="row justify-content-center gallery-filters">
          <div class="col-md-10 col-xl-5">
            <div class="filters small-text text-lg-right">
              <a href="#" data-filter="*" class="active selected">Portfolio</a>
              <a href="#" data-filter=".carpinteria">aluminio y cristalería</a>
              <a href="#" data-filter=".estructuras">estructuras metálicas</a>
              <a href="#" data-filter=".puertas">puertas</a>
              <a href="#" data-filter=".muebles">muebles</a>
              <a href="#" data-filter=".lumon">cristal de LUMON</a>
              <a href="#" data-filter=".acero">acero inoxidable</a>
            </div>
          </div>
        </div>
        <div class="row isotope-wrapper masonry-layout c-gutter-0 c-mb-0" data-filters=".gallery-filters">

          <!-- Carpinteria de aluminio start -->
          <div class="col-xl-3 col-sm-6 carpinteria">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "mallorquinas_rptrdx", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 carpinteria">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "barandilla-3", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 carpinteria">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "barandilla-2", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="col-xl-3 col-sm-6 carpinteria">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "carpinteria_aluminio_can_nebot_y2wguk", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="col-xl-3 col-sm-6 carpinteria">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "carpinteria_aluminio_formentera_opjxtz", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 carpinteria">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "carpinteria_fachada_can_nebot_h627v2", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Carpinteria de aluminio end -->
          <!-- Estructuras start -->
          <div class="col-xl-3 col-sm-6 estructuras">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "santiago-steinkamp-t1zo-_yx5c0-unsplash_lhzfjn", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 estructuras">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "spencer-davis-yxP-M0JFDTM-unsplash_bfumvw", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Estructuras end -->
          <!-- Puertas start -->
          <div class="col-xl-3 col-sm-6 puertas">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "puertas_correderas_con_motor_ud6jmr", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 puertas">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "puertas_correderas_corten_hntqw5", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Puertas end -->
          <!-- Muebles start -->
          <div class="col-xl-3 col-sm-6 muebles">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "estructura_mesa_porche_casa_campo_bnpy8i", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 muebles">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "mueble-2", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>

          <!-- Muebles end -->
          <!-- Lumon start -->
          <div class="col-xl-3 col-sm-6 lumon">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "cerramientos_lumon_terraza_ldrstp", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 lumon">
            <div class="vertical-item item-gallery content-absolute text-center">
              <div class="item-media ds">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "fotos-de-porches-056_ln0zhs", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Lumon end -->
          <!-- Barandillas start -->
          <div class="col-xl-3 col-sm-6 acero">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "barandilla_escalera_cristal_w8wutb", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 acero">
            <div class="vertical-item item-gallery content-absolute text-center ds">
              <div class="item-media">
                <%= link_to gallery_path, data: { turbolinks: false } do  %>
                  <%= cl_image_tag "tusik-only-CQGZ9jA1s7Q-unsplash_oifsga", height: 480, width: 480, crop: "fill" %>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Barandillas end -->
        </div>
        <!-- .isotope-wrapper-->
      </div>
      <div class="d-none d-lg-block divider-20"></div>
    </div>
  </div>
</section>

app/views/pages/about.html.erb
<%= render 'breadcrumbs' %>

 <section class="ds ms s-pt-0 s-pb-20 s-py-md-20 s-pt-lg-100 s-pb-lg-75 c-my-5 c-gutter-100 founder-bio" id="founder">
  <div class="cover-image s-cover-right"></div>
  <!-- half image background element -->
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6 order-md-2">
        <%= cl_image_tag "christopher-burns-8KfCR12oeUM-unsplash_aapbdm", height: 480, width: 480, crop: "fill" %>
        <!-- half image source -->
      </div>
      <div class="col-md-6 order-md-1">
        <div class="item-content">
          <h2>
            RGM Ibiza Metal
          </h2>

          <p class="small-text color-main">

          </p>
          <p>
            <strong style="color: #f9a34f;">EMPRESA FAMILIAR CON MAS DE 50 AÑOS DE EXPERIENCIA</strong> . Nos hemos ido adaptando a las necesidades de nuestro mercado sin perder la fabricación artesanal a medida de toda la vida. Si necesitas <strong style="color: #f9a34f">asesoramiento y realizar un trabajo a tu gusto</strong> que se adapte a lo que realmente necesitas, ésta es tu empresa para realizar tu proyecto o idea. Somos un equipo de 3 personas formadas bajo la supervisión de un gran profesional del sector metalúrgico y carpintería metálica. A sus espaldas hay proyectos realizados en nuestra querida isla de ibiza, tales como estación marítima de formentera, muro cristal de la policía nacional, columnas de acero del diario de ibiza, recinto ferial  y un largo etc… <strong style="color: #f9a34f;">Nuestro compromiso y transparencia</strong> con el cliente es la base de la relación que ofrecemos a nuestros clientes . Al trabajar de manera <strong style="color: #f9a34f;">artesanal  a medida</strong>, los tiempos de ejecución no son cortos pero el resultado es artesano y profesional. Además <strong style="color: #f9a34f;">ofrecemos servicio postventa</strong>, algo muy poco frecuente. <%= link_to "Contacta", contact_path %>  con nosotros sin compromiso y te asesoraremos de la mejor forma dando opciones a tus proyectos . Contamos en el equipo con un interiorista y paisajista para poder dar mayor cobertura  y atención .

          </p>
          <div class="media-item">
            <img src="images/signature.png" alt="">

          </div>
        </div>
      </div>
    </div>
    <div class="d-none d-lg-block divider-10"></div>
  </div>
</section>

<%= render 'services' %>

app/views/shared/_header-multi-page.html.erb
<!-- header with three Bootstrap columns - left for logo, center for navigation and right for includes-->
<div class="header_absolute">
  <header class="page_header ds justify-nav-center">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-xl-2 col-lg-4 col-11">
          <a href="./" class="logo">
            <%= image_tag "logo-rgm.png", alt: "alttext" %>
          </a>
        </div>
        <div class="col-xl-8 col-lg-6 col-1 text-sm-center">
          <!-- main nav start -->
          <nav class="top-nav">
            <ul class="nav sf-menu">
              <li>
                <%= link_to "Home", root_path %>
              </li>

              <li>
                <%= link_to "About", about_path  %>
              </li>

              <li>
                <%= link_to "Gallery", gallery_path  %>
              </li>
              <li>
                <a href="#services">Services</a>
              </li>
              <li>
                <a href="#founder">Founder</a>
              </li>
              <li>
                <a href="#team">Team</a>
              </li>
              <li>
                <a href="#contacts">Contacts</a>
              </li>
              <li>
                <a href="#blog">Blog</a>
              </li>

            </ul>
          </nav>
          <!-- eof main nav -->
        </div>
        <div class="col-xl-2 col-lg-3 text-md-left text-xl-right d-none d-lg-block">

          <ul class="top-includes">


            <li>

              <span class="social-icons">
                <a href="#" class="fa fa-facebook border-icon rounded-icon" title="facebook"></a>
                <a href="#" class="fa fa-twitter border-icon rounded-icon" title="twitter"></a>
                <a href="#" class="fa fa-google border-icon rounded-icon" title="google"></a>
              </span>
            </li>


          </ul>

        </div>
      </div>
    </div>
    <!-- header toggler -->
    <span class="toggle_menu">
      <span></span>
    </span>
  </header>
</div>

app/views/shared/_header.html.erb
<div class="header_absolute">
  <header class="page_header ds justify-nav-center">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-xl-2 col-lg-3 col-11">
          <%= link_to root_path, data: { turbolinks: false }, class: "logo" do  %>
            <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
             width="150" height="150" viewBox="0 0 2480.000000 1231.000000"
             preserveAspectRatio="xMidYMid meet">
              <metadata>
              Created by potrace 1.16, written by Peter Selinger 2001-2019
              </metadata>
              <g transform="translate(0.000000,1231.000000) scale(0.100000,-0.100000)"
              fill="#fff" stroke="none">
                <path d="M1500 11328 l0 -363 1108 -461 1107 -461 3 -2742 c1 -1507 -1 -2741
                -5 -2741 -15 0 -2168 -281 -2190 -286 l-23 -4 0 -315 0 -315 3608 2 3607 3
                1845 708 1845 707 1830 -701 c1006 -386 1834 -705 1840 -710 5 -5 1512 -9
                3617 -9 l3608 0 0 318 0 317 -1078 139 c-592 76 -1092 141 -1110 144 l-32 5 2
                2741 3 2741 1105 461 1105 460 3 362 2 362 -3607 0 -3608 0 -1825 -2211
                c-1004 -1215 -1834 -2222 -1846 -2236 l-20 -26 -1820 2209 c-1001 1215 -1829
                2221 -1839 2236 l-20 27 -3607 1 -3608 0 0 -362z m14580 -17 l0 -280 -1626
                -1703 c-895 -937 -1660 -1737 -1701 -1778 -56 -55 -25 -14 118 160 572 695
                3203 3880 3206 3880 2 0 3 -126 3 -279z m-5719 -1711 c876 -1064 1613 -1960
                1638 -1990 l45 -55 -62 60 c-33 33 -781 814 -1661 1735 l-1601 1675 0 280 0
                280 24 -25 c13 -14 740 -896 1617 -1960z m-6641 935 l0 -435 -22 9 c-29 11
                -1933 804 -2008 837 l-55 23 1043 1 1042 0 0 -435z m19429 431 c-3 -3 -1677
                -703 -2036 -852 l-33 -13 0 435 0 434 1037 0 c570 0 1034 -2 1032 -4z m-13932
                -1948 l2542 -1823 -2 -909 -2 -909 -2580 -533 c-1419 -293 -2588 -533 -2597
                -533 -17 -1 -18 163 -18 3305 l0 3306 58 -41 c31 -23 1201 -861 2599 -1863z
                m9023 -1403 c0 -1860 -4 -3305 -9 -3305 -8 0 -5132 1054 -5178 1065 l-23 5 0
                904 0 904 2598 1865 c1428 1026 2600 1865 2605 1866 4 1 7 -1486 7 -3304z
                m-5260 -1340 l0 -885 -585 0 -585 0 0 885 0 885 585 0 585 0 0 -885z m-680
                -945 c-14 -5 -835 -246 -1826 -535 l-1801 -525 -998 2 -999 3 2569 531 2570
                532 255 0 c157 0 245 -3 230 -8z m3243 -522 l2588 -533 -1005 -3 -1004 -2
                -1829 534 -1828 535 245 1 245 0 2588 -532z m-3170 301 c-4 -4 -820 -318
                -1813 -697 -993 -380 -1813 -693 -1822 -697 -17 -7 -18 9 -18 254 l0 261 23 5
                c12 4 834 243 1827 534 l1805 527 3 -90 c1 -49 -1 -93 -5 -97z m1881 -349
                c998 -291 1817 -530 1820 -530 3 0 6 -117 6 -260 0 -143 -1 -260 -2 -260 -2 0
                -822 314 -1823 698 l-1820 697 -3 93 c-1 50 0 92 3 92 3 0 822 -238 1819 -530z
                m-10534 -370 l0 -120 -897 1 c-494 1 -887 4 -873 6 32 5 1741 231 1758 232 9
                1 12 -29 12 -119z m18280 0 c470 -61 864 -112 875 -114 11 -2 -388 -4 -887 -5
                l-908 -1 0 120 0 121 33 -6 c17 -3 417 -55 887 -115z"/>
                <path d="M4150 2736 c-240 -45 -438 -182 -494 -343 -31 -87 -38 -195 -43 -643
                -5 -479 4 -723 32 -818 40 -132 139 -244 278 -312 101 -49 176 -69 287 -77
                166 -11 303 32 400 125 l52 50 17 -42 c10 -22 21 -51 25 -63 7 -23 8 -23 222
                -23 l214 0 0 570 0 570 -390 0 -390 0 0 -165 0 -165 66 0 65 0 -3 -202 c-3
                -232 -11 -260 -73 -277 -70 -19 -109 7 -125 84 -13 62 -9 1286 4 1323 10 26
                54 52 90 52 14 0 38 -11 53 -24 l28 -24 3 -206 3 -206 336 0 336 0 -6 163 c-6
                177 -30 299 -73 373 -53 93 -195 194 -341 243 -142 48 -418 65 -573 37z"/>
                <path d="M1930 1650 l0 -1060 335 0 335 0 0 470 0 470 43 0 c23 0 58 -8 77
                -18 55 -27 58 -52 59 -514 l1 -408 311 0 310 0 -3 432 c-3 424 -3 434 -25 474
                -47 88 -98 130 -207 170 -34 13 -54 24 -46 27 8 3 38 11 65 17 161 40 215 145
                215 417 0 325 -114 495 -367 548 -103 22 -398 35 -775 35 l-328 0 0 -1060z
                m797 655 c45 -30 56 -76 51 -221 -3 -102 -7 -136 -21 -157 -18 -28 -69 -47
                -124 -47 l-33 0 0 226 0 227 51 -6 c28 -4 63 -14 76 -22z"/>
                <path d="M5380 1650 l0 -1060 295 0 295 0 2 625 3 625 104 -608 c58 -334 106
                -615 109 -624 4 -16 23 -18 212 -18 189 0 208 2 212 17 3 10 49 298 104 641
                l99 623 3 -640 2 -641 295 0 295 0 0 1060 0 1060 -434 0 -433 0 -16 -97 c-8
                -54 -39 -259 -68 -455 -30 -197 -56 -354 -60 -350 -3 4 -36 187 -73 407 -37
                220 -72 421 -77 448 l-11 47 -429 0 -429 0 0 -1060z"/>
                <path d="M8210 1650 l0 -1060 335 0 335 0 0 1060 0 1060 -335 0 -335 0 0
                -1060z"/>
                <path d="M9120 1650 l0 -1060 533 0 c658 0 747 9 854 82 56 38 87 80 115 158
                22 62 23 78 23 340 0 266 -1 277 -24 334 -40 101 -112 164 -231 201 -30 10
                -59 20 -63 22 -5 3 24 16 64 30 149 50 189 100 210 261 18 147 -6 321 -58 429
                -34 69 -118 147 -199 185 -131 62 -309 78 -846 78 l-378 0 0 -1060z m789 667
                c24 -8 41 -24 55 -52 18 -35 21 -56 20 -165 -3 -190 -23 -220 -151 -220 l-43
                0 0 225 0 225 43 -1 c23 0 57 -5 76 -12z m11 -800 c22 -7 40 -23 48 -41 19
                -38 28 -290 14 -380 -16 -97 -36 -117 -139 -131 l-53 -7 0 286 0 286 48 -1
                c26 0 63 -5 82 -12z"/>
                <path d="M10870 1650 l0 -1060 335 0 335 0 0 1060 0 1060 -335 0 -335 0 0
                -1060z"/>
                <path d="M11730 2490 l0 -220 215 0 c118 0 215 -4 215 -9 0 -5 -110 -312 -245
                -682 l-245 -674 0 -157 0 -158 610 0 610 0 0 215 0 215 -240 0 c-132 0 -240 2
                -240 5 0 3 108 287 240 632 l240 626 -2 211 -3 211 -577 3 -578 2 0 -220z"/>
                <path d="M13121 1663 c-90 -577 -166 -1054 -169 -1061 -3 -10 67 -12 344 -10
                l349 3 17 165 c9 91 17 173 17 183 1 15 13 17 111 17 61 0 110 -1 110 -2 0 -2
                7 -77 15 -168 8 -91 15 -173 15 -182 0 -17 23 -18 340 -18 320 0 340 1 340 18
                0 16 -353 2028 -365 2080 l-5 22 -478 0 -477 0 -164 -1047z m694 231 c26 -243
                51 -453 61 -511 l6 -33 -101 0 -101 0 0 33 c1 64 99 761 106 754 2 -2 15 -111
                29 -243z"/>
                <path d="M15260 1650 l0 -1060 295 0 295 0 2 625 3 625 104 -608 c58 -334 106
                -615 109 -624 4 -16 23 -18 212 -18 189 0 208 2 212 17 3 10 49 298 104 641
                l99 623 3 -640 2 -641 295 0 295 0 0 1060 0 1060 -434 0 -433 0 -16 -97 c-8
                -54 -39 -259 -68 -455 -30 -197 -56 -354 -60 -350 -3 4 -36 187 -73 407 -37
                220 -72 421 -77 448 l-11 47 -429 0 -429 0 0 -1060z"/>
                <path d="M17540 1650 l0 -1060 575 0 575 0 0 215 0 215 -240 0 -240 0 0 225 0
                225 205 0 205 0 0 210 0 210 -205 0 -205 0 0 190 0 190 215 0 215 0 0 220 0
                220 -550 0 -550 0 0 -1060z"/>
                <path d="M18700 2490 l0 -220 195 0 195 0 0 -840 0 -840 330 0 330 0 0 840 0
                840 195 0 195 0 0 220 0 220 -720 0 -720 0 0 -220z"/>
                <path d="M20161 1663 c-90 -577 -166 -1054 -169 -1061 -3 -10 67 -12 344 -10
                l349 3 17 165 c9 91 17 173 17 183 1 15 13 17 111 17 61 0 110 -1 110 -2 0 -2
                7 -77 15 -168 8 -91 15 -173 15 -182 0 -17 23 -18 340 -18 320 0 340 1 340 18
                0 16 -353 2028 -365 2080 l-5 22 -478 0 -477 0 -164 -1047z m694 231 c26 -243
                51 -453 61 -511 l6 -33 -101 0 -101 0 0 33 c1 64 99 761 106 754 2 -2 15 -111
                29 -243z"/>
                <path d="M21750 1650 l0 -1060 530 0 530 0 0 215 0 215 -195 0 -195 0 0 845 0
                845 -335 0 -335 0 0 -1060z"/>
              </g>
            </svg>
          <% end %>
        </div>
        <div class="col-xl-8 col-lg-6 col-1 text-sm-center">
          <!-- main nav start -->
          <nav class="top-nav">
            <ul class="nav sf-menu">
              <li class="">
                <%= link_to "Inicio", root_path, data: { turbolinks: false } %>
              </li>
              <li>
                <a href="#services">Servicios</a>
                <ul>
                  <li>
                    <%= link_to "Carpintería de aluminio y cristaleria", service_1_path, data: { turbolinks: false }  %>
                  </li>
                  <li>
                    <%= link_to "Estructuras metálicas", service_2_path, data: { turbolinks: false }  %>
                  </li>
                  <li>
                    <%= link_to "Soldadores", service_3_path, data: { turbolinks: false }  %>
                  </li>
                  <li>
                    <%= link_to "Cortinas de cristal LUMON", service_4_path, data: { turbolinks: false }  %>
                  </li>
                  <li>
                    <%= link_to "Mobiliario", service_5_path, data: { turbolinks: false }  %>
                  </li>
                </ul>
              </li>
              <li>
                <%= link_to "Sobre nosotros", about_path, data: { turbolinks: false } %>
              </li>
              <!-- gallery -->
              <li>
                <%= link_to "Portfolio", gallery_path, data: { turbolinks: false } %>
              </li>
              <!-- eof Gallery -->

              <!-- contacts -->
              <li>
                <%= link_to "Contact", contact_path, data: { turbolinks: false } %>
              </li>
              <!-- eof contacts -->
            </ul>


          </nav>
          <!-- eof main nav -->
        </div>
        <div class="col-xl-2 col-lg-3 text-md-left text-xl-right d-none d-lg-block">

          <ul class="top-includes">


            <li>

              <span class="social-icons">
                <a href="https://www.facebook.com/rgmibizametalico" target="_blank" class="fa fa-facebook border-icon rounded-icon" title="facebook"></a>
<!--                 <a href="#" class="fa fa-twitter border-icon rounded-icon" title="twitter"></a>
                <a href="#" class="fa fa-google border-icon rounded-icon" title="google"></a> -->
              </span>
            </li>


          </ul>

        </div>
      </div>
    </div>
    <!-- header toggler -->
    <span class="toggle_menu">
      <span></span>
    </span>
  </header>
</div>